# Generated by Django 6.1.1 on 2026-09-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('finance', '0003_payment'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'fee_structure'), name='unique_student_fee_structure'),
        ),
    ]
