# Generated by Django 6.1.1 on 2026-09-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('finance', '0004_studentfee_unique_student_fee_structure'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(fields=('academic_year', 'school_class', 'fee_type'), name='unique_fee_structure_per_class_year_type'),
        ),
    ]
