# Generated by Django 6.1.1 on 2026-09-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_feestructure_unique_fee_structure_per_class_year_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentfee',
            name='unique_student_fee_structure',
        ),
    ]
