# Generated by Django 6.1.1 on 2026-09-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('finance', '0006_remove_studentfee_unique_student_fee_structure'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_fee_per_year'),
        ),
    ]
