# Generated by Django 6.1.1 on 2026-09-22 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_assignments', to='academics.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_assignments', to='academics.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_assignments', to='teachers.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('section', 'academic_year'), name='unique_class_teacher_per_section_year')],
            },
        ),
    ]
